[tool.poetry]
name = "evaluator"
version = "0.1.0"
description = ""
authors = ["Maria <a.vicidomini36@studenti.unisa.it>"]
packages = [{include = "evaluator", from = "src"}]

[tool.poetry.dependencies]
python = "^3.13"
instructor = "^1.15.4"
python-dotenv = "^1.2.2"
anthropic = "^0.115.0"
openai = "^2.44.0"
pydantic = "^2.13.4"
requests = "^2.34.2"
tqdm = "^4.69.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
