[tool.poetry]
name = "staraptor"
version = "0.1.0"
description = ""
authors = ["Maria <a.vicidomini36@studenti.unisa.it>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.2.2"
storage = { path = "libs/storage", develop = true }
analyzer = { path = "libs/analyzer", develop = true }
orchestrator = {path = "libs/orchestrator", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
