#!/usr/bin/env bash

# Risolve eventuali link simbolici per individuare la vera cartella dello script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
PROJECT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# Esegue Poetry puntando alla cartella radice del progetto
poetry --directory "$PROJECT_DIR" run python "$PROJECT_DIR/StARAPTOR.py" "$@"